### ISSUE TITLE
Compiling with latest yosys and black screen SDRAM

### ISSUE THREAD

**Issue by emard** [Speccery/icy99#6]
HI

There are some problems compiling with latest
yosys/nextpnr (ULX3S). I used diamond and I got it boot
only using BRAM version. If I use SDRAM, there's
only black screen, I tried loading ROMs from ESP32
but still no boot. Memory mapping is very complex for
me to understand what goes where, can you revive/freshen
this TI99/4A, its very nice project.

**Comment by Speccery** [comment]
Thanks for the report, I will take a look. I haven't tested the project recently with recent tool versions, will give it a try. Thanks again! And yes, memory mapping is complex with this project :)

**Comment by emard** [comment]
It would be helpful a bit of readme or similar comment note in the source
what address in 32-bit space (as seen from ESP32 spi-ram interface) is
mapped to what device/address on TI99/4A (ram rom grom cart dsr)

I can try with latest yosys to check if it can compile at least BRAM version.
when I last tried, only bram with diamond compilation was the only combination
that boots

**Comment by Speccery** [comment]
Hi @emard thanks, yes it would be good to provide more information. I appreciate your feedback. I took a look at this yesterday evening and ran out of time to really dig in. I will improve the documentation with a memory map when I have more time.

I also got the black screen. For me I found out that the design works with the toolchain I have installed on my macOS if in the **top_ulx3s.v** file I comment out line 10:
`// define CONSOLE_ROM_IN_SDRAM  1   // 8K`
This puts the console ROM in address zero to BRAM and that works for me. The console ROM size is 8K and it resides at SDRAM address zero. 

In the **esp32/osd/osd.py** file there is a method **save_mem**. I added at the very end of osd.py two calls:
```
run.save_mem("r0.bin", 0, 8192)
run.save_mem("rg.bin", 65536, 24*1024)
``` 
to save the contents stored into SDRAM. The data at address zero for me is corrupted, it does not match the ROM image. However, the GROM image, 24k of data at address 64k in SDRAM seems to be correct. I was also able to load several cartridges (they go to SDRAM) and they were working.

Please note that I was using my development branch which is not exactly the same codebase in the master branch, but close. I can't believe it's been two years since I've worked on this. Anyway, once I understand what is going on I will fix this and improve the documentation as well.

**Comment by emard** [comment]
good news is that today's yosys compiles icy99 source
and it boots after I comment those 2 lines:

//`define CONSOLE_ROM_IN_SDRAM  1   // 8K
//`define CONSOLE_GROM_IN_SDRAM 1   // 24K

commenting only this line is not enough to boot

//`define CONSOLE_ROM_IN_SDRAM  1   // 8K

in my testing

**Comment by emard** [comment]
When commeted above 2 lines
loading first cart it tried "Snake Plisskan"
works, obviously runing from SDRAM

**Comment by Speccery** [comment]
Thanks for testing, that's encouraging. I take it @emard you're using daily builds of APIO, or the toolchain itself? I have pretty busy days at the moment but will try to test in the evening.

**Comment by emard** [comment]
No apio, I'm using daily tgz of toolchain, I just extract to any
directory and in shell PATH=$PATH:/any/directory/bin/

**Comment by Speccery** [comment]
Hi @emard sorry for the huge delay. I fixed the build - currently running without SDRAM. I used the oss-cad-suite 2023-11-18 to build it. Need to get the SDRAM working again though. The IFS1P3BX component doesn't seem to exist anymore. I will also try to ping you in discord.
